# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'
  # vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreInstaller@0
  displayName: Install ASP.NET Core
  inputs:
    packageType: 'sdk'
    version: '2.2.3'
    
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build API ($(buildConfiguration))'

- task: DotNetCoreCLI@2
  displayName: Run Backend Unit Tests
  inputs:
    command: test
    projects: '**/*UnitTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run Backend Integration Tests
  inputs:
    command: test
    projects: '**/*IntegrationTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
