# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'
  # vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreInstaller@0
  displayName: Install ASP.NET Core SDK
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview6-012264'
    
- task: DotNetCoreCLI@2
  displayName: DotNet Build Backend
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run Backend Unit Tests
  inputs:
    command: test
    projects: 'tests/*UnitTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run Backend Integration Tests
  inputs:
    command: test
    projects: 'tests/*IntegrationTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: Run Backend Functional Tests
  inputs:
    command: test
    projects: 'tests/*FunctionalTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Zip Backend
  inputs:
    command: publish
    publishWebProjects: False
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Backend'
  inputs:
    artifactName: 'WebAPI'

- task: AzureRmWebAppDeployment@4
  displayName: 'Publish To Azure Apps'
  inputs:
    azureSubscription: 'AzureResources'
    WebAppName: 'RecipeManager'
    UseWebDeploy: True
    DeploymentType: webDeploy
    Package: $(System.ArtifactsDirectory)/**/*.zip
