# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'
  # vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:

# This specific SDK is needed for the integration tests
- task: DotNetCoreInstaller@0
  displayName: Install ASP.NET Core SDK
  inputs:
    packageType: 'sdk'
    version: '2.2.105'
    
- task: DotNetCoreCLI@2
  displayName: DotNet Build
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run Backend Unit Tests
  inputs:
    command: test
    projects: '**/*UnitTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Run Backend Integration Tests
  inputs:
    command: test
    projects: '**/*IntegrationTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: Run Backend Functional Tests
  inputs:
    command: test
    projects: '**/*FunctionalTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: |
    cd ./RecipeManager/ClientApp
    npm install
  displayName: Run 'npm install'

- script: |
    cd ./RecipeManager/ClientApp
    npm run test
  displayName: Run Frontend Tests (Unit, Integration, BDD)

- task: DotNetCoreCLI@2
  displayName: DotNet Publish
  inputs:
    command: publish
    publishWebProjects: False
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    artifactName: 'MainArtifact'

- task: AzureRmWebAppDeployment@4
  displayName: 'Publish To Azure Apps'
  inputs:
    azureSubscription: 'AzureResources'
    WebAppName: 'RecipeManager'
    Package: $(System.ArtifactsDirectory)/**/*.zip
