version: '3.4'

services:

  webapi:
    image: fernandr/recipemanager
    container_name: recipemanager-webapi
    environment:
      - "ConnectionStrings:AppDB=Host=db;Port=5432;Database=recipemanager;Username=postgres;Password=SuperSecure"
      - "DatabaseOptions:Type=PostgreSQL"
      - "DatabaseOptions:Migrate=true"
      - "DatabaseOptions:Delete=false"
      - "DatabaseOptions:Create=false"
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
